name: DerpyBackpack
author: KZ5EE
version: 1.0
main: com.fnordo.main.Main

commands:
    bp:
        description: Open da bakpaaaack!


permissions:
    dbp.use:
        default: false
    dbp.slots.18:
        default: false
    dbp.slots.27:
        default: false
    dbp.slots.36:
        default: false
    dbp.slots.45:
        default: false
    dbp.slots.54:
        default: false
